### ISSUE TITLE
CSV data collection

### ISSUE THREAD

**Issue by do-lab-ku** [do-lab-ku/Spearmint#1]
Currently we only save to CSV manually, it would be good to do this automatically after a sweep.

**Comment by Mamba-Grant** [comment]
Right now we actually don't "export" any data, only use the default sqlite db that qcodes requires to do data collection on. After a sweep finishes we should automatically export the data in csv format. When we run measurements using the queue, we should automatically save at the end of the queue.

**Comment by Mamba-Grant** [comment]
Feature implemented- renamed "origin files" to "exported files" as that makes more sense. Autosaves are made to this directory automatically after every sweep. Tested with Sweep0D (time). **Needs to be tested with queue.**

I believe we should auto save on the completion of every single sweep, although perhaps we could implement a setting to change this behavior to export on the final sweep of the queue.

**Comment by Mamba-Grant** [comment]
Closing issue for now, I will re-open it if we want to add a setting as discussed in previous comment. Right now the philosophy is that more saves is better than few, but we shall see.
